### ISSUE TITLE
Push notifications stopped working again on ios

### ISSUE THREAD

**Issue by king8084** [vbresults/mobile-apps#78] opened 2016-04-26 21:59 UTC
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### Are you running the latest version of the app(s) and add-on?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps-for-xenforo/issues)?
Yes

### 1.1. If so, tell us about the problem
-- Details --
Push notifications stopped working again
### 1.2. Which platform(s) does your issue occur on?
iOS/Android/Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.1.40)
- Android App: (e.g. 1.1.40)
- Platform (choose): XenForo, vBulletin, WordPress
- Add-on Version: (e.g. 1.1.40)
- XenForo Version: (e.g. 1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
-- Details --

### 1.5. Is there an error message involved?  If so, please paste
-- Details --

## 2. Are you requesting a new feature?
Yes/No

### 2.1. If so, delete everything above #2, describe your idea
-- Details --

## 3. Do you have a question?
Yes/No

### 3.1. If so, enter your question
-- Details --

**Comment by vbresults** [comment] 2016-04-27 12:11
Duplicate of #75 , re-opening that ticket

**Closed by vbresults** 2016-04-27 12:11 UTC
