### ISSUE TITLE
Theme light for IOS & Background color for Android

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps#66] opened 2016-04-05 17:19 UTC
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
I set theme "light". For IOS, the status bar text is white in color, which causes the text not visible (my background is white). But when I switched to theme "dark", the status bar text is back to original.
But then, for Android, the title bar background also turn dark in color even though I only switch the theme to "dark". Plus, the title bar background color can't be set.

### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (1.2)
- Android App: (1.2)
- Platform (choose): XenForo
- Add-on Version: (1.2)
- XenForo Version: (1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
Switch the theme & background color.

### 1.5. Is there an error message involved?  If so, please paste
No

**Comment by vbresults** [comment] 2016-04-08 17:52
iOS is working as intended but on Android I need clarification; the status bar text color cannot be manipulated on older android versions (pre-lollipop) regardless of what the theme is.

I want to distinguish between the status bar (which has the time etc.) and the title bar (which has the page title).  On lollipop and newer the background color is used in the status bar too.

What version of Android are you running?

**Comment by bloh2** [comment] 2016-04-09 13:52
5.1.1 Samsung Note 2

No matter what I set for the background color, the title bar background color will remain Black.
If I don't set the background color, it will then follow the theme. If theme is dark, then the background color is dark. And if the theme is light, the background color will be white. Supposedly, the theme shouldn't affect the background color of title bar.

IOS works fine.

**Comment by vbresults** [comment] 2016-04-18 08:13
@bloh2 I found what you were mentioning in regards to iOS (the theme color is forced to light due to a bug in the Xen add-on that incorrectly sets a default value for style properties which overrides the colors set on our site).

**Comment by bloh2** [comment] 2016-04-18 08:19
For android, the title bar background color can't be set. For IOS, it can be set.

And somehow the theme option is affecting the android title bar background color when the background color is not set.

And if background color is set for android, the title bar will always be black in color.

On 18 Apr 2016, at 4:13 PM, vB Results, LLC. <notifications@github.com<mailto:notifications@github.com>> wrote:


@bloh2<https://github.com/bloh2> I found what you were mentioning in regards to iOS (the theme color is forced to light due to a bug in the Xen add-on that incorrectly sets a default value for style properties which overrides the colors set on our site).

-

**Comment by vbresults** [comment] 2016-04-18 16:32
Looking into this, the Android theme is working as intended but there's another bug -- if the theme is light, it has a light grey background color by default is no background color is set.

If the theme is dark, but there is a background color is set, the background color can't be changed -- and that is because the background isn't applied after the theme change -- that is the bug here.

Thank you for reporting this; it has been fixed in 1.2.1 (:

**Closed by vbresults** 2016-04-18 16:32 UTC
Labels: android, bug
